initial commit for event bus doc
Kros-sk/Kros.BusEventDoc pull request #1
Opened 2019-02-19 06:11 UTC by FriStud

A light version of event docs. Also it requires refactoring. Just html format of UI, no styling, just skeleton to get stuff collaborating.

2019-02-19 12:18 UTC, Burgyn requested changes
- [ ] Fix warning:
> Warning	MSB3270	There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference

- [ ] Remove unused usings in files
- [ ] Turn on documentation generation in projects.
- [ ] Okomentovať jednotlivé triedy. (Všetky public triedy a metódy v hlavných projektoch musia byť okomentované)
- [ ] Pre json je typickejšie, že je camelcase
- [ ] Demo teraz má 3 eventy, ale v sekcií definition sa zobrazujú len dve.
- [ ] Testy na mojom PC neprechádzajú.

2019-02-19 12:18 UTC, Burgyn commented on tests/Kros.EvenBusDoc.Test.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Rename project `Kros.EventBusDoc.Test` to `Kros.EventBusDoc.Generator.Tests`

2019-02-19 12:18 UTC, Burgyn commented on tests/Kros.EvenBusDoc.Test.csproj
> +    <DocumentationFile>C:\Develop\bus\tests\resources\XML\Kros.EvenBusDoc.Test.xml</DocumentationFile>
Add suppress warnings 1701;1702;1591. 1591 - suppress XML missing commentar warning in test project.

```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>C:\Develop\bus\tests\resources\XML\Kros.EvenBusDoc.Test.xml</DocumentationFile>
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>
```

2019-02-19 12:18 UTC, Burgyn commented on tests/EventBusDocTypeResolverShould.cs
> +        private const string XML_PATH = @"C:\Develop\bus\tests\resources\XML\Kros.EvenBusDoc.Test.xml";
Remove `XML_PATH` constant and load resource from assembly.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/Middleware/Extensions/KrosEventBusDocBuilderExtensions.cs
> +    public static class KrosEventBusDocBuilderExtensions
Premenoval by som tú triedu štandardne `ApplicationBuilderExtensions`

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/Middleware/Extensions/EventBusDocGenSerCollExtensions.cs
> +        public static void ConfigureEventBusDocGen(
Táto metóda nie je potrebná.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/Middleware/Extensions/EventBusDocGenSerCollExtensions.cs
> +            services.Configure<MvcOptions>(c =>
Myslím si, že to nepotrebujeme. Ak to naozaj nepotrebujeme tak to odstráňme a aj tú triedy, ktorú k tomu vytvárame.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/Middleware/Extensions/EventBusDocGenSerCollExtensions.cs
> +            // Register generator and it's dependencies
Takéto komentáre sa snažíme minimalizovať. často časom prestanú byť aktuálne. Ak je to možné, radšej daný kus kódu zabaliť do metódy, ktorú výstižne pomenujeme.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentAnnotation/EventBusConsumeerAttribute.cs
> +    public class EventBusConsumeerAttribute : EventBusBaseAttribute
Dve ee v slove consumeer :-)

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentAnnotation/EventBusCommandSenderAttribute.cs
> +    public class EventBusCommandSenderAttribute : EventBusBaseAttribute
Asi by sme si mali sadnúť aj s @satano a dohodnúť si názvy. 
Takto mi to nesedí, ale neviem či môj návrh je pelší :-(
Môj návrh:
```
[assembly: EventBusCommandPublish(EventType = typeof(ICommandOne))]
[assembly: EventBusCommandSubscribe(EventType = typeof(ICommandTwo))]
[assembly: EventBusMessagePublish(EventType = typeof(IMessageOne))]
[assembly: EventBusMessageSubscribe(EventType = typeof(IMessageTwo))]
```

2019-02-19 12:18 UTC, Burgyn commented on tests/EventBusDocTypeResolverShould.cs
> +        #region Tests For Collections Events, Commands, ResolvedTypes
Testy z tohto regiónu by mali byť vo vlastnej triede, pretože pravdepodobne testujú niečo iné.

2019-02-19 12:18 UTC, Burgyn commented on tests/EventBusDocTypeResolverShould.cs
> +        #region Inline Tests For Reading Summary & Remarks From Xml
Testy v tomto regióne testujú `BXmlReader` tak majú byť v samostatnej triede.

2019-02-19 12:18 UTC, Burgyn commented on tests/EventBusDocTypeResolverShould.cs
> +
Prázdny riadok na konci metódy nepoužívame. Je to na veľa miestach.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/XmlReader/BXmlReader.cs
> +            try
`Try` tu nie je potrebný.

Ak by aj bol potrebný tak exception sa nepreposiela `throw e`, ale len `throw`. Ak chceš vysvetlím rozdiel.

2019-02-19 12:18 UTC, Burgyn commented on tests/EventBusDocTypeResolverShould.cs
> +    public class EventBusDocTypeResolverShould
Chýba mi tu taký jasný test, kde nasimulujem assembly s atribútmi, zavolám danú metódu a dostanem json. Následne ten json porovnám s nejakým očakávaným.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/Middleware/EventBusDocOptions.cs
> +        public string RouteTemplate { get; set; } = "busent/{documentName}/busent.json";
Naozaj `{documentName}`, alebo radšej `{version}`?

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/Middleware/EventBusDocGeneratorMiddleware.cs
> +        private readonly ILogger<EventBusDocGeneratorMiddleware> _logger;
V tejto triede je veľa nepoužívaných premenných.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/Middleware/EventBusDocGeneratorMiddleware.cs
> +            catch (UnknownBusentDocument)
Táto výnimka sa reálne nikde nevyhadzuje, takže ju nemusíme odchytávať. Taktiež môžme zmazať danú triedu.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/Middleware/EventBusDocGeneratorMiddleware.cs
> +        private bool RequestingBusentDocument(HttpRequest request, out string documentName)
Naozaj `documentName`? Nie náhodou `version`?

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/Middleware/Extensions/KrosEventBusDocBuilderExtensions.cs
> +namespace Kros.EventBusDoc.Generator.Middleware.Extensions
Častokrát sa robí to, že táto extension sa dáva do namespace `Microsoft.AspNetCore.Builder`. Aby človek v `Startup` triede nemusel pridávať ďalšie namespaces.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/Middleware/Extensions/EventBusDocGenSerCollExtensions.cs
> +    public static class EventBusDocGenSerCollExtensions
Túto triedy by som nazval štandartne `ServiceCollectionExtensions` a namespace premenoval na `Microsoft.Extensions.DependencyInjection`.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/Helpers/Extensions.cs
> +    public static class Extensions
Nazval by som to `TypeExtensions`. Niektoré metódy sa nepoužívajú. To čo sa nepoužíva tak preč s tým.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/Helpers/Utils.cs
> +    public static class Utils
Je tu jediná metóda a tá sa nepoužíva, takže kľudne preč s ňou.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/Helpers/Extensions.cs
> +    public static class Extensions
podľa mňa môže byť táto trieda `internal`.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/XmlReader/XmlReadExtensions.cs
> +    public static class XmlReadExtensions
Podľa mňa môže byť táto trieda `internal`.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/XmlReader/IXmlReader.cs
> +    public interface IXmlReader
Nebolo by lepšie to nazvať `IXmlDocumentationReader`?
Taktiež si myslím, že tieto veci môžu byť `internal`.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/XmlReader/EXmlTypeTag.cs
> +    public enum EXmlTypeTag
Nazval by som to `XmlDocumentationType` a dal by som to `internal`.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/XmlReader/EXmlTypeTag.cs
> +        P = 1,
Nepoužívajme takéto skratky. Dajme tu normálne `Property`, `Class`

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/XmlReader/BXmlReader.cs
> +    public class BXmlReader : IXmlReader
Nazval by som to `XmlDocumentationReader` a dal by som to ako `internal`.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/XmlReader/BXmlReader.cs
> +        public string GetSummary(string item)
Nepoužíva sa, preč s ňou.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/XmlReader/BXmlReader.cs
> +        public string GetSummary(Type type, PropertyInfo property = null)
Používame Expression-bodied members:
```suggestion
        public string GetSummary(Type type, PropertyInfo property = null)
          => GetInnerElementString(type, EXmlTypeTag.Summary, property);
```

Aj na iných miestach kde sa to nachádza.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/Scourers/ScourerBase.cs
> +    public abstract class ScourerBase : IScourer
`internal`?

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/Scourers/ScourerBase.cs
> +            return (type.IsPrimitive || IsRegistered(type) || (type.BaseType is null && !type.IsInterface) || (type == typeof(string))) ? true : false;
V konvenciach máme, že máme maximálnu dĺžku riadku 130 znakov.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/Scourers/AttributeFetcher.cs
> +    public class AttributeFetcher : IAttributeFetcher
Niektoré metódy tejto triedy sa nikde nepoužívajú.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/Scourers/AttributeFetcher.cs
> +namespace Kros.EventBusDoc.Generator.BusentScour.Scourers
Všetky triedy v tomto namespace by mohli byť `internal`.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/Generators/DeclarativeGenerator.cs
> +                _document = GenerateFormat("natvrdo");
??

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/Generators/DeclarativeGenerator.cs
> +        public OpenApiDocument GetBusent(string docName, string host = null, string basePath = null)
Nie je nikde použitá.

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/Generators/DeclarativeGenerator.cs
> +                Version = "v0",
Je možné to z vonku nastaviť?

2019-02-19 12:18 UTC, Burgyn commented on src/Kros.EventBusDoc.Generator/BusentScour/Generators/DeclarativeGenerator.cs
> +                descObj.Properties = descObj.Properties.Append(
nestačí tu zavolať nasledovné:
```
descObj.Properties.Append(
                        new Property()
                        {
                            Description = _xmlReader.GetSummary(item, prop),
                            Name = prop.Name,
                            IsPrimitive = prop.PropertyType.IsPrimitive,
                            Type = prop.PropertyType.GetName()
                        }
                    );
```

bez toho priradenia?

2019-02-26 08:57 UTC, satano commented
Tento PR rušíme a bude sa pozerať [UI Resolution](https://github.com/Kros-sk/Kros.BusEventDoc/pull/5).

2019-02-26 08:57 UTC, closed without merging